package com.serialization;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.Serializable;

class Animal_1 {
	int i =10;
	public Animal_1() {
		System.out.println("animal default constructor");
	}
}
class Dog_0 extends Animal_1 implements Serializable{
	int j = 20;
	public Dog_0() {
		System.out.println("dog default constructor");
	}
}
public class InheritanceInSerilization_2 {

	public static void main(String[] args) throws Exception {
		// INSTANCE CONTOLL FLOW
		/*
		even though parent class doent implement serilizable, we can serilize chuld class object
		if child class implment seriazable intrege to serialize child class , parent class need not be serilizable
		*/
		
		Dog_0 dog = new Dog_0();
		dog.i = 888;
		dog.j = 999;
		
		System.out.println(dog.i +" ......."+dog.j);
		FileOutputStream fos = new FileOutputStream("D:\\java\\inheritance2.txt");
		ObjectOutputStream oos = new ObjectOutputStream(fos);
		oos.writeObject(dog);
		
		FileInputStream fis = new FileInputStream("D:\\java\\inheritance2.txt");
		ObjectInputStream ois = new ObjectInputStream(fis);
		Dog_0 dog2 = (Dog_0) ois.readObject();
		System.out.println(dog2.i +" ......."+dog2.j);
		
		/* IF CHILD CLASS IMPLEMENT SERILIZAVBLE THEN NEED OT TO BE PARENT CLASS IMPLEMENT SERILIZABLE
		 * 
		 * 
		 * 
		 * SERILIZATION : is any variable come inheriting from non-serilzanble parent then jvm ignore original value
		 * and save default value to the file
		 * 
		 * 
		 * DESRILIZATION : AT THE TIME OF DSERILIZATION JVM WILL CHECK IS ANY CLASS NON-SERILZABLE OR NOT, IF 
		 * ANY PARENT CLASS IS NON SERILIZABLE THEN JVM WILL EXECUTE INSTANCE CONTROL FLOW,
		 * IN EVRY NON SERILIZABLE PARENT , AND SHEAR ITS INSTANCE VARIABLE TO THE CURRENT OBJECT
		 * 
		 * 
		 * WHILE EXECUTING INSTANCE CONTROL FLOW, OF NON SERILIZABLE PARENT , JVM WILL ALWYAS CALL 
		 * NO ARGUMENT CONSTRUCTOR, 
		 * HENCE EVERY NON SERILIZABLE CLASS, SHOULD CMPULSORY CONTAIN NON ARGUMENT CONSTRUCTOR,
		 * IT MAY BE DEFAULT CONSTRUCTOR GENERATED BY COMPLIER OR COSTUMIZED CONSTRUCTOR , EXPLACITY 
		 * PROVIDE BY PROGRAMMER,
		 * OTHER WISE WE WILL GET RUN TIME EXCEPTION, SAYING INVILIDE CLASS EXCEPTION
		 */

	}

}
